
""""""""""""""""""""""""""""""
"" TODO
""""""""""""""""""""""""""""""

" Figure out how to make hlsearch with more comfortable colors
" How to remove trailing spaces?
" Configure wrapping well
" Setup autocompletion, linting and navigation
" Put words in quotes with a command
" Vim Autosave
" Insert one line above shortcut
" Understand how set hidden works
" Investigate how to do custom mappings (nerdtree, rg, fzf, etc)
" Configure vim-airline
" Configure vim-startify

call plug#begin('~/.vim/plugged')

""""""""""""""""""""""""""""""
"" Key Bindings
""""""""""""""""""""""""""""""
    let mapleader = ','
	noremap <leader>/ :Commentary<cr>

	" don't use arrowkeys

	noremap <Up> <NOP>
	noremap <Down> <NOP>
	noremap <Left> <NOP>
	noremap <Right> <NOP>

	" really, just don't
	inoremap <Up>    <NOP>
	inoremap <Down>  <NOP>
	inoremap <Left>  <NOP>
	inoremap <Right> <NOP>

	" disable useless ex-mode
	nnoremap Q <nop>

	nnoremap <leader>o o<Esc>
	nnoremap <leader>O O<Esc>

""""""""""""""""""""""""""""""
"" General Options
""""""""""""""""""""""""""""""
	" explicitly tell vim that the terminal supports 256 colors
	set t_Co=256

	" faster redrawing
	set ttyfast 

	" autoreload files
	set autoread

	" set X lines to the cursors - when moving vertical
    set scrolloff=7 

	set encoding=UTF-8

	" set history length
	set history=1000
    
	" enhanced command line completion
	set wildmenu 
	" complete files like a shell
    set wildmode=list:longest 

	" make backspace behave in a sane manner
	set backspace=indent,eol,start 

	" use MacOS clipboard
	set clipboard=unnamed

	" enable mouse if possible
    if has('mouse')
        set mouse=a
    endif

	set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
    set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

	" allow to navigate one character more at the EOL
	set virtualedit=onemore


	set timeoutlen=500
	
	" update time after editing stop to call plugins
    set updatetime=300

	"Reduce delay when switching out of insert mode
	set ttimeoutlen=5

	" set vim's shell to default's shell
    set shell=$SHELL
	
	" avoid hit-enter prompts
    if v:version > 800
		set shortmess+=c
	endif

	" Unknown
	if v:version > 800
		set diffopt+=vertical,iwhite,internal,algorithm:patience,hiddenoff
	endif
    set hidden " current buffer can be put into background
	

	""""""""""""""""""""""""""
    " Appearence
	""""""""""""""""""""""""""
		" set good colors
		if v:version > 800
			set termguicolors
		endif

		" show the status line all the time
	    set laststatus=2 
	
		" set terminal title
		set title 
	
		" show vertical rules
		set colorcolumn=120
	
		" open new split panes to right and bottom, which feels more natural than Vim’s default:
		set splitbelow
		set splitright
	
		" show line numbers
		set number

		" highlight syntax
		syntax on

		" show incomplete commands
		set showcmd 

		" don't show which mode 
		set noshowmode 

		" command bar height
		set cmdheight=1 

		" show matching braces
		set showmatch 
	
		" how many tenths of a second to blink when matching brackets 
		set mat=2 
	
		" always show left-side bar (for git, linters, etc)
		if v:version > 800
			set signcolumn=yes
		endif

	""""""""""""""""""""""""""
    " Tab control
	""""""""""""""""""""""""""
		" tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
		set smarttab 
	
		" the visible width of tabs
		set tabstop=4 
	
		" edit as if the tabs are 4 characters wide
		set softtabstop=4 
	
		" number of spaces to use for indent and unindent
		set shiftwidth=4 
	
		" round indent to a multiple of 'shiftwidth'
		set shiftround 
	
		" automatically set indent of new line
		set autoindent 

	""""""""""""""""""""""""""
    " Wrapping
	""""""""""""""""""""""""""
	
		" turn on line wrapping
		set wrap 

		" wrap lines when coming within n characters from side
		set wrapmargin=8 
	
		" set soft wrapping
		set linebreak 
	
		" show ellipsis at breaking   
		set showbreak=… 

		" autowrap text at width 120 (if possible)
		set textwidth=120
	
	""""""""""""""""""""""""""
    " Search and Replace
	""""""""""""""""""""""""""
	
		" case insensitive searching
		set ignorecase 

		" case-sensitive if expresson contains a capital letter
		set smartcase 
	
		" highlight search results
		set hlsearch 
	
		" set incremental search, like modern browsers
		set incsearch 
	
		" don't redraw while executing macros
		set nolazyredraw 

		set magic " Set magic on, for regex

		if (has('nvim'))
			" show results of substition as they're happening
			" but don't open a split
			set inccommand=nosplit
		endif

	""""""""""""""""""""""""""
	" Error bells
	""""""""""""""""""""""""""
	    set noerrorbells
		set visualbell
		set t_vb=

    """"""""""""""""""""""""""
	" Invisible characters
    """"""""""""""""""""""""""
	set list
    set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
    set showbreak=↪
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mhinz/vim-startify'
Plug 'moll/vim-bbye'
Plug 'tpope/vim-commentary'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tmux-plugins/vim-tmux'
Plug 'chriskempson/base16-vim'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
        let g:fzf_layout = { 'down': '~25%' }

        if isdirectory(".git")
            " if in a git project, use :GFiles
            nmap <silent> <leader>t :GitFiles --cached --others --exclude-standard<cr>
        else
            " otherwise, use :FZF
            nmap <silent> <leader>t :FZF<cr>
        endif
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
	let g:WebDevIconsOS = 'Darwin'
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
    let g:DevIconsEnableFoldersOpenClose = 1
    let g:DevIconsEnableFolderExtensionPatternMatching = 1
    let NERDTreeDirArrowExpandable = "\u00a0" " make arrows invisible
    let NERDTreeDirArrowCollapsible = "\u00a0" " make arrows invisible
    let NERDTreeNodeDelimiter = "\u263a" " smiley face

	augroup nerdtree
        autocmd!
        autocmd FileType nerdtree setlocal nolist " turn off whitespace characters
        autocmd FileType nerdtree setlocal nocursorline " turn off line highlighting for performance
    augroup END

	" Toggle NERDTree
    function! ToggleNerdTree()
        if @% != "" && @% !~ "Startify" && (!exists("g:NERDTree") || (g:NERDTree.ExistsForTab() && !g:NERDTree.IsOpen()))
            :NERDTreeFind
        else
            :NERDTreeToggle
        endif
    endfunction
    " toggle nerd tree
    nmap <silent> <leader>k :call ToggleNerdTree()<cr>
    " find the current file in nerdtree without needing to reload the drawer
    nmap <silent> <leader>y :NERDTreeFind<cr>

    let NERDTreeShowHidden=1
    " let NERDTreeDirArrowExpandable = '▷'
    " let NERDTreeDirArrowCollapsible = '▼'
    let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }

Plug 'tpope/vim-fugitive'
	nmap <silent> <leader>gs :Gstatus<cr>
	nmap <leader>ge :Gedit<cr>
	nmap <silent><leader>gr :Gread<cr>
	nmap <silent><leader>gb :Gblame<cr>

	" Plug 'tpope/vim-rhubarb' " github extension for fugitive
	Plug 'junegunn/gv.vim'
	Plug 'sodapopcan/vim-twiggy'
	Plug 'tommcdo/vim-fubitive'
	
call plug#end()

colorscheme gruvbox
" vim:set foldmethod=marker foldlevel=0
