[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml",
]

[window]
option_as_alt = "Both"

[keyboard]

bindings = [
  { key = "h", mods = "Command", chars = "\u001bh"},
  { key = "j", mods = "Command", chars = "\u001bj"},
  { key = "k", mods = "Command", chars = "\u001bk"},
  { key = "l", mods = "Command", chars = "\u001bl"}
]

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "1", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$'
command = { program = "/opt/homebrew/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "2", mods = "Control" }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 17

# Colors
# [colors]

# Primary colors
# [colors.primary]
# background = "0x080c10"
# foreground = "0xd8dee9"

# # Normal colors
# [colors.normal]
# black = "0x2c2c3d"
# red = "0xff6e6e"
# green = "0x9ec875"
# yellow = "0xffa759"
# blue = "0x70a7d4"
# magenta = "0xd291e0"
# cyan = "0x96e0e0"
# white = "0xd8dee9"

# # Bright colors
# [colors.bright]
# black = "0x414166"
# red = "0xff8d8d"
# green = "0xb3d987"
# yellow = "0xffc57f"
# blue = "0x9bb3d3"
# magenta = "0xffa1ff"
# cyan = "0x9cd8d8"
# white = "0xffffff"


