# Change prefix to ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Resize with Meta-HJKL
unbind-key -T root M-j
unbind-key -T root M-k
unbind-key -T root M-h
unbind-key -T root M-l

bind-key -T root M-j resize-pane -D
bind-key -T root M-k resize-pane -U
bind-key -T root M-h resize-pane -L
bind-key -T root M-l resize-pane -R


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Make the first window number start at 1
set -g base-index 1

# Make pane numbering consistent with windows
setw -g pane-base-index 1

# Renumber windows when a window is closed
# This guarantees it will be easier for you to switch
# between windows as you keep opening and closing them
set -g renumber-windows on

# Vi-mode keys
setw -g mode-keys vi

# Turn on mouse support
set -g mouse on

# Improve colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Fix EventFocus/EventLost events in ViM and others
# https://github.com/tmux-plugins/vim-tmux-focus-events
set -g focus-events on

# Set scrollback buffer to 10000
set -g history-limit 10000

# Custom view for tmux-sidebar plugin
set -g @sidebar-tree-command 'tree -C -L 1'

#### Plugins #####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'jbnicolai/tmux-fpp'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'

