# General

export CDPATH=".:~/code"

export DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib"
export CPATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/"


export CPPFLAGS="-I/usr/include $CPPFLAGS"

# Zlib (required for python building)
export LDFLAGS="-L/usr/local/opt/zlib/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/zlib/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig $PKG_CONFIG_PATH"

# Readline
export LDFLAGS="-L/usr/local/opt/readline/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/readline/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig $PKG_CONFIG_PATH"

# PostgreSQL

export PATH="/usr/local/opt/postgresql@12/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/postgresql@12/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/postgresql@12/include $CPPFLAGS"
export CPPFLAGS="-I/usr/local/opt/postgresql@12/include/postgresql/server $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@12/lib/pkgconfig $PKG_CONFIG_PATH"

# MySQL

export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/mysql-client/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/mysql-client/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig $PKG_CONFIG_PATH"


# CoreUtil
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"


# OpenSSL

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig $PKG_CONFIG_PATH"


#If you need to have gettext first in your PATH run:
#  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
#
#For compilers to find gettext you may need to set:
#  export LDFLAGS="-L/usr/local/opt/gettext/lib"
#
#  export CPPFLAGS="-I/usr/local/opt/gettext/include"
#

#If you need to have sqlite first in your PATH run:
#  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile
#
#For compilers to find sqlite you may need to set:
#  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
#  export CPPFLAGS="-I/usr/local/opt/sqlite/include"
#
#For pkg-config to find sqlite you may need to set:
#  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"


#Python has been installed as
#  /usr/local/bin/python3
#
#Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
#`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
#  /usr/local/opt/python/libexec/bin
#
#If you need Homebrew's Python 2.7 run
#  brew install python@2
#
#You can install Python packages with
#  pip3 install <package>
#They will install into the site-package directory
#  /usr/local/lib/python3.7/site-packages
#
#See: https://docs.brew.sh/Homebrew-and-Python
#
#
#
#By default, binaries installed by gem will be placed into:
#  /usr/local/lib/ruby/gems/2.6.0/bin
#
#You may want to add this to your PATH.
#
#ruby is keg-only, which means it was not symlinked into /usr/local,
#because macOS already provides this software and installing another version in
#parallel can cause all kinds of trouble.
#
#If you need to have ruby first in your PATH run:
#  echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
#
#For compilers to find ruby you may need to set:
#  export LDFLAGS="-L/usr/local/opt/ruby/lib"
#  export CPPFLAGS="-I/usr/local/opt/ruby/include"
#
#For pkg-config to find ruby you may need to set:
#  export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
