# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ ! -d ${HOME}/.zplugin ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
fi

# bindkey "^R" fzf-history-widget
### Added by Zplugin's installer
source '/Users/damamaty/.zplugin/bin/zplugin.zsh'
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

# Aliases

alias cat='bat'
alias ping='prettyping --nolegend'
alias ls='exa'
alias vim="nvim"
alias vimdiff="nvim -d"
alias tmux="tmux -u"

# Exports

export EDITOR="nvim"
export TERM=xterm-256color
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}' --bind 'ctrl-e:toggle-preview'"
export FZF_CTRL_R_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}'"
# Select all entries with 'CTRL-A'
[ -n "$TMUX" ] && export TERM=screen-256color

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Fix backspace in vi mode
bindkey -v '^?' backward-delete-char
bindkey '^[^?' backward-kill-word

# ZSH Options
unsetopt correct_all

# Plugins
# # Disable bracketing paste because it causes issues with autosuggestions.
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

# Add 256color if terminal the current terminal supports it.
zplugin load "chrissicool/zsh-256color"
# Dircolors
zplugin ice atclone"dircolors -b LS_COLORS > c.zsh" atpull'%atclone' pick"c.zsh"
zplugin load "trapd00r/LS_COLORS"

# Shell colors
# zplugin ice pick"async.sh" src"scripts/base16-gruvbox-dark-pale.sh"
zplugin load "chriskempson/base16-shell"

zplugin ice wait"1" lucid
zplugin light lukechilds/zsh-nvm

# zplugin ice atclone"./libexec/pyenv init - > zpyenv.zsh" \
#     atinit'export PYENV_ROOT="$PWD"' atpull"%atclone" \
#     as'command' pick'bin/pyenv' src"zpyenv.zsh" nocompile'!'
# zplugin light pyenv/pyenv
#

t() {
    SESSION="$1"
    if [ -z "$1" ]; then
        if [ -n "$( tmux ls )" ]; then
            SESSION=$(tmux ls | sed 's/:.*//g' | fzf --height 20% --layout=reverse --prompt "Choose session:" --preview 'tmux ls | grep {}' --preview-window up:1 --print-query | \tail -n1)
        fi
    fi

    if [ -n "$SESSION" ]; then
        if [ -z "$TMUX" ];then
            tmux attach -t "$SESSION" || tmux new -s "$SESSION"
        else
            tmux switch-client -t "$SESSION" || tmux -2 new-session -d -s "$SESSION" && tmux switch-client -t "$SESSION"
        fi
    fi
}

# 2x ctrl-d to exit ...
export IGNOREEOF=4

# bash like ctrl-d wrapper for IGNOREEOF
setopt ignore_eof
function bash-ctrl-d() {
  if [[ $CURSOR == 0 && -z $BUFFER ]]
  then
    [[ -z $IGNOREEOF || $IGNOREEOF == 0 ]] && exit
    if [[ "$LASTWIDGET" == "bash-ctrl-d" ]]
    then
      (( --__BASH_IGNORE_EOF <= 0 )) && exit
    else
      (( __BASH_IGNORE_EOF = IGNOREEOF ))
    fi
  fi
}
zle -N bash-ctrl-d
bindkey "^d" bash-ctrl-d

zplugin light romkatv/powerlevel10k

export CLICOLOR=YES

# Syntax Highlighting (should always be at the end)
zplugin ice wait"0" atinit"zpcompinit; zpcdreplay" lucid
zplugin light zdharma/fast-syntax-highlighting

export PATH="/Users/damamaty/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
